name: Release
on:
    workflow_call:
        inputs:
            is_prerelease:
                description: Pre-release
                type: boolean
                required: true
            release_tag:
                description: Release tag
                type: string
                required: true
            release_body:
                description: Release description
                type: string
                required: true
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Download Windows artifacts
              uses: actions/download-artifact@v4
              with:
                  name: tauri-app-windows-${{ github.event.inputs.release_tag || github.ref_name }}
                  path: artifacts/windows
            - name: Download Ubuntu artifacts
              uses: actions/download-artifact@v4
              with:
                  name: tauri-app-ubuntu-${{ github.event.inputs.release_tag || github.ref_name }}
                  path: artifacts/ubuntu
            - name: Download macOS artifacts
              uses: actions/download-artifact@v4
              with:
                  name: tauri-app-macos-${{ github.event.inputs.release_tag || github.ref_name }}
                  path: artifacts/macos
            - name: Upload release build artifacts to GitHub Release
              uses: softprops/action-gh-release@v2.3.2
              with:
                  name: ${{ inputs.release_tag }}
                  tag_name: ${{ inputs.release_tag }}
                  body: ${{ inputs.release_body }}
                  draft: false
                  prerelease: ${{ inputs.is_prerelease }}
                  make_latest: true
                  files: artifacts/**/*
